statsd_host: 127.0.0.1
statsd_port: 8125
items:
- name: net.ens3.rx_bytes
  type: file
  interval: 1
  path: /sys/class/net/ens3/statistics/rx_bytes
  metric: counter
  delta: true
- name: net.ens3.tx_bytes
  type: file
  interval: 1
  path: /sys/class/net/ens3/statistics/tx_bytes
  metric: counter
  delta: true
- name: memory
  type: memory
  interval: 10
  metric: gauge
  delta: false
- name: cpu
  type: cpu
  interval: 1
  path: cpu
  metric: counter
  delta: true
- name: uptime
  type: uptime
  interval: 10
  metric: gauge
  delta: false
